config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'posts#index'

  resources :posts do
    collection do
      get 'search'
    end
  end

  resources :users, only: :show

  resources :conditions do
    collection do
      get 'temp'
      get 'weight'
      get 'blood_max'
      get 'blood_min'
      get 'com'
    end
  end

  resources :medicines
  get 'tags/:tag', to: 'medicines#index', as: :tag
end

app/models/condition.rb
class Condition < ApplicationRecord
  belongs_to :user

  with_options presence: true do
    validates :start_time
    validates :temperature
    validates :weight
    validates :blood_max
    validates :blood_min
    validates :condition

    with_options numericality: { message: "半角数字で入力してください" } do
      validates :temperature
      validates :weight
      validates :blood_max
      validates :blood_min
    end

    validates :condition, :numericality => { :less_than_or_equal_to => 5, :message => "５以下の数字を入力してください" }
  end
end

app/controllers/conditions_controller.rb
class ConditionsController < ApplicationController
  before_action :condition_set, only: [:show, :destroy, :edit, :update]

  def index
    @data = Condition.where(user_id: current_user).order("start_time DESC").page(params[:page]).per(5)
    @nickname = current_user.nickname
    @user = current_user
  end

  def new
    @data = Condition.new
  end

  def create
    @data = Condition.create(condition_params)
    if @data.save
      @data.temperature += params[:temperature].to_f
      @data.weight += params[:weight].to_f
      redirect_to conditions_path
    else
      render :new
    end
  end

  def show
    @nickname = current_user.nickname
  end

  def edit
    if current_user.id != @data.user_id
      redirect_to conditions_path
    end
  end

  def update
    if @data.update(condition_params)
      redirect_to conditions_path, notice: "編集しました"
    else
      render :edit
    end
  end

  def destroy
    @data.destroy
    redirect_to conditions_path, notice: "削除しました"
  end

  def temp
  end

  def weight
  end

  def blood_max
  end

  def blood_min
  end

  def com
  end

  private

  def condition_params
    params.require(:condition).permit(:start_time, :temperature, :weight, :blood_max, :blood_min, :condition, :memo).merge(user_id: current_user.id)
  end

  def condition_set
    @data = Condition.find(params[:id])
  end
end

app/helpers/conditions_helper.rb
module ConditionsHelper
end

app/views/conditions/blood_max.html.erb
<div class="blood-chart">
  <h1 class="graph-title">＜最高血圧グラフ＞</h1>
  <br>
  <%= line_chart Condition.where(user_id: current_user).pluck(:start_time, :blood_max), xtitle: "日付", ytitle: "最高血圧", curve: false, min: 50, max: 200, id: "column-chart", width: "100%", height: "300px" %>
</div>
<br>
<div class="show-link">
  <%= link_to 'Back', :back, class:"back" %>
</div>

app/views/conditions/blood_min.html.erb
<div class="blood-chart">
  <h1 class="graph-title">＜最低血圧グラフ＞</h1>
  <br>
  <%= line_chart Condition.where(user_id: current_user).pluck(:start_time, :blood_min), xtitle: "日付", ytitle: "最低血圧", curve: false, min: 30, max: 150, id: "column-chart", width: "100%", height: "300px" %>
</div>
<br>
<div class="show-link">
  <%= link_to 'Back', :back, class:"back" %>
</div>

app/views/conditions/com.html.erb
<div class="com-chart">
  <h1 class="graph-title">＜体調グラフ＞</h1>
  <br>
  <%= line_chart Condition.where(user_id: current_user).pluck(:start_time, :condition), xtitle: "日付", ytitle: "体調", curve: false, min: 1, max: 5, id: "column-chart", width: "100%", height: "300px" %>
</div>
<br>
<div class="show-link">
  <%= link_to 'Back', :back, class:"back" %>
</div>

app/views/conditions/edit.html.erb
<%= form_with(model: @data, local: true) do |f| %>

  <% if @data.errors.any? %>
    <div class="error-alert">
      <ul>
        <% @data.errors.full_messages.each do |message| %>
        <li class='error-message'><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <br>

  <div class="date">
    <%= f.label :【日付】 %>
    <br>
    <%= f.date_field :start_time, class:"date-form" %>
  </div>
  <br>

  <div class="temperature">
    <%= f.label :【体温】 %>
    <br>
    <%= f.text_field :temperature,placeholder: "半角数字（小数点第１位まで）を入力", class:"temperature-form" %>
  </div>
  <br>

  <div class="weight">
    <%= f.label :【体重】 %>
    <br>
    <%= f.text_field :weight,placeholder: "半角数字（小数点第１位まで）を入力", class:"weight-form" %>
  </div>
  <br>

  <div class="blood">
    <%= f.label :【最高血圧】 %>
    <br>
    <%= f.text_field :blood_max, placeholder: "半角数字を入力", class:"blood-form" %>
    <br>
    <%= f.label :【最低血圧】 %>
    <br>
    <%= f.text_field :blood_min, placeholder: "半角数字を入力", class:"blood-form" %>
  </div>
  <br>

  <div class="condition">
    <p class="condition-title">【体調】</p>
    <%= f.radio_button :condition, :"1", class:"condition-input" %>
    <%= f.label :condition, "非常に悪い", {value: 1} %>

    <%= f.radio_button :condition, :"2", class:"condition-input" %>
    <%= f.label :condition, "悪い", {value: 2} %>

    <%= f.radio_button :condition, :"3", class:"condition-input" %>
    <%= f.label :condition, "普通", {value: 3} %>

    <%= f.radio_button :condition, :"4", class:"condition-input" %>
    <%= f.label :condition, "良い", {value: 4} %>

    <%= f.radio_button :condition, :"5", class:"condition-input" %>
    <%= f.label :condition, "非常に良い", {value: 5} %>
  </div>
  <br>

  <div class="memo">
    <%= f.label :【メモ】 %>
    <br>
    <%= f.text_field :memo, class:"memo-form" %>
  </div>
  <br>


  <div class="submit">
    <%= f.submit "投稿" %>
  </div>
  <br>

  <div class="show-link">
    <%= link_to 'Back', :back, class:"back" %>
  </div>

<% end %>

app/views/conditions/index.html.erb
<p id="notice"><%= notice %></p>

<div class="posts-list">
  <h1 class="mypage-title">＜<%= @nickname %>さんの直近の体調記録＞</h1>
  <br>
  <% if @data.any? %>
    <table>
      <thead>
        <tr>
          <th>日付</th>
          <th>体温</th>
          <th>体重</th>
          <th>最高血圧</th>
          <th>最低血圧</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @data.each do |data| %>
          <tr>
            <td><%= data.start_time.strftime("%Y-%m-%d") %></td>
            <td><%= data.temperature.floor(1) %>℃</td>
            <td><%= data.weight.floor(1) %>kg</td>
            <td><%= data.blood_max %>mmHg</td>
            <td><%= data.blood_min %>mmHg</td>
            <td><%= link_to '詳細', data %></td>
            <td><%= link_to '編集', edit_condition_path(data.id) %></td>
            <td><%= link_to '削除',condition_path(data.id), method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  <% else %>
    まだ記録がありません
  <% end %>
  <%= paginate @data %>
  <br>
  <%= link_to "記録する", new_condition_path, class: "condition-post" %>
  <br>
  <br>
  <div class="temp-chart">
    <h1>＜各項目の推移＞</h1>
    <ul>
      <li><%= link_to '体温', temp_conditions_path, class:"graph" %></li>
      <li><%= link_to '体重', weight_conditions_path, class:"graph" %></li>
      <li><%= link_to '最高血圧', blood_max_conditions_path, class:"graph" %></li>
      <li><%= link_to '最低血圧', blood_min_conditions_path, class:"graph" %></li>
      <li><%= link_to '体調', com_conditions_path, class:"graph" %></li>
    </ul>
  </div>
  <br>

  <div class="mypage-link">
    <%= link_to 'マイページへ戻る', "users/#{@user.id}", class:"back" %>
  </div>
</div>

app/views/conditions/new.html.erb
<%= form_with(model: @data, local: true) do |f| %>

  <% if @data.errors.any? %>
    <div class="error-alert">
      <ul>
        <% @data.errors.full_messages.each do |message| %>
        <li class='error-message'><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <br>

  <div class="date">
    <%= f.label :【日付】 %>
    <br>
    <%= f.date_field :start_time, class:"date-form" %>
  </div>
  <br>

  <div class="temperature">
    <%= f.label :【体温】 %>
    <br>
    <%= f.text_field :temperature,placeholder: "半角数字（小数点第１位まで）を入力", class:"temperature-form" %>
  </div>
  <br>

  <div class="weight">
    <%= f.label :【体重】 %>
    <br>
    <%= f.text_field :weight,placeholder: "半角数字（小数点第１位まで）を入力", class:"weight-form" %>
  </div>
  <br>

  <div class="blood">
    <%= f.label :【最高血圧】 %>
    <br>
    <%= f.text_field :blood_max, placeholder: "半角数字を入力", class:"blood-form" %>
    <br>
    <%= f.label :【最低血圧】 %>
    <br>
    <%= f.text_field :blood_min, placeholder: "半角数字を入力", class:"blood-form" %>
  </div>
  <br>

  <div class="condition">
    <p class="condition-title">【体調】</p>
    <%= f.radio_button :condition, :"1", class:"condition-input" %>
    <%= f.label :condition, "非常に悪い", {value: 1} %>

    <%= f.radio_button :condition, :"2", class:"condition-input" %>
    <%= f.label :condition, "悪い", {value: 2} %>

    <%= f.radio_button :condition, :"3", class:"condition-input" %>
    <%= f.label :condition, "普通", {value: 3} %>

    <%= f.radio_button :condition, :"4", class:"condition-input" %>
    <%= f.label :condition, "良い", {value: 4} %>

    <%= f.radio_button :condition, :"5", class:"condition-input" %>
    <%= f.label :condition, "非常に良い", {value: 5} %>
  </div>
  <br>

  <div class="memo">
    <%= f.label :【メモ】 %>
    <br>
    <%= f.text_field :memo, class:"memo-form" %>
  </div>
  <br>


  <div class="submit">
    <%= f.submit "投稿" %>
  </div>
  <br>

  <div class="show-link">
    <%= link_to 'Back', :back, class:"back" %>
  </div>

<% end %>

app/views/conditions/show.html.erb
<p id="notice"><%= notice %></p>

<div class="show">
  <h1 class="mypage-title">＜<%= @nickname %>さんの<%= @data.start_time.strftime("%m/%d") %>の体調記録＞</h1>
  <br>
  <table>
    <tr>
      <th><strong>【日付】</strong></th><td><%= @data.start_time.strftime("%Y-%m-%d") %></td>
    </tr>

    <tr>
      <th><strong>【体温】</strong></th><td><%= @data.temperature %>℃</td>
    </tr>

    <tr>
      <th><strong>【体重】</strong></th><td><%= @data.weight %>kg</td>
    </tr>

    <tr>
      <th><strong>【最高血圧】</strong></th><td><%= @data.blood_max %></td>
    </tr>

    <tr>
      <th><strong>【最低血圧】</strong></th><td><%= @data.blood_min %></td>
    </tr>

    <tr>
      <th><strong>【体調】</strong></th><td><%= @data.condition %></td>
    </tr>

    <tr>
      <th><strong>【メモ】</strong></th><td><%= @data.memo %></td>
    </tr>

  </table>
</div>
<br>

<div class="show-link">
  <%= link_to '編集', edit_condition_path(@data), class:"edit" %>
  <%= link_to 'Back', conditions_path, class:"back" %>
</div>

app/views/conditions/temp.html.erb
<div class="temp-chart">
  <h1 class="graph-title">＜体温グラフ＞</h1>
  <br>
  <%= line_chart Condition.where(user_id: current_user).pluck(:start_time, :temperature), xtitle: "日付", ytitle: "体温", curve: false, min: 35, max: 40, id: "column-chart", width: "100%", height: "300px" %>
</div>
<br>
<div class="show-link">
  <%= link_to 'Back', :back, class:"back" %>
</div>

app/views/conditions/weight.html.erb
<div class="weight-chart">
  <h1 class="graph-title">＜体重グラフ＞</h1>
  <br>
   <%= line_chart Condition.where(user_id: current_user).pluck(:start_time, :weight), xtitle: "日付", ytitle: "体重", curve: false, min: 30, max: 120, id: "column-chart", width: "100%", height: "300px" %>
</div>
<br>
<div class="show-link">
  <%= link_to 'Back', :back, class:"back" %>
</div>