config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'posts#index'

  resources :posts do
    collection do
      get 'search'
    end
  end

  resources :users, only: :show

  resources :conditions do
    collection do
      get 'temp'
      get 'weight'
      get 'blood_max'
      get 'blood_min'
      get 'com'
    end
  end

  resources :medicines
  get 'tags/:tag', to: 'medicines#index', as: :tag
end

app/models/medicine.rb
class Medicine < ApplicationRecord
  belongs_to :user
  has_one_attached :image

  acts_as_taggable #タグ付け機能のGem追加

  with_options presence: true do
    validates :start_time
    validates :name
  end
end

app/controllers/medicines_controller.rb
class MedicinesController < ApplicationController
  before_action :medicine_set, only: [:show, :destroy, :edit, :update]

  def index
    @nickname = current_user.nickname
    @user = current_user
    if params[:tag]
      @medicines = Medicine.tagged_with("#{params[:tag]}").where(user_id: current_user).order("start_time DESC").page(params[:page]).per(3)
    else
      @medicines = Medicine.where(user_id: current_user).order("start_time DESC").page(params[:page]).per(3)
    end
  end

  def new
    @medicine = Medicine.new
  end

  def create
    @medicine = Medicine.create(medicine_params)
    if @medicine.save
      redirect_to medicines_path
    else
      render :new
    end
  end

  def show
    @nickname = current_user.nickname
  end

  def destroy
    @medicine.destroy
    redirect_to medicines_path, notice:"削除しました"
  end

  def edit
    if current_user.id != @medicine.user_id
      redirect_to medicines_path
    end
  end

  def update
    if @medicine.update(medicine_params)
      redirect_to medicines_path, notice: "編集しました"
    else
      render 'edit'
    end
  end

  private

  def medicine_params
    params.require(:medicine).permit(:name, :start_time, :memo, :image, :tag_list).merge(user_id: current_user.id)
  end

  def medicine_set
    @medicine = Medicine.find(params[:id])
  end
end

app/helpers/medicines_helper.rb
module MedicinesHelper
end

app/views/medicines/edit.html.erb
<%= form_with(model: @medicine, local: true) do |f| %>

  <% if @medicine.errors.any? %>
    <div class="error-alert">
      <ul>
        <% @medicine.errors.full_messages.each do |message| %>
        <li class='error-message'><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <br>

  <div class="date">
    <%= f.label :【処方日】 %>
    <br>
    <%= f.date_field :start_time, class:"date-form" %>
  </div>
  <br>

  <div class="medicine-name">
    <%= f.label :【処方名】 %>
    <br>
    <%= f.text_field :name, placeholder: "薬の名前を入力", class:"name-form" %>
  </div>
  <br>

  <div class="medicine-file">
    <%= f.label :【画像】 %>
    <br>
    <%= f.file_field :image, class:"file-form" %>
  </div>
  <br>

  <div class="medicine-tag">
    <%= f.label :【タグ】 %>
    <br>
    <%= f.text_field :tag_list, value: @medicine.tag_list.join(','), placeholder: "症状別にタグ付け", class:"tag-form" %>
    <p>※タグを複数加える場合は「,」でつなげてください。<br>　例）発熱,頭痛</p>
  </div>
  <br>

  <div class="memo">
    <%= f.label :【メモ】 %>
    <br>
    <%= f.text_field :memo, class:"memo-form" %>
  </div>
  <br>


  <div class="submit">
    <%= f.submit "登録" %>
  </div>
  <br>

  <div class="show-link">
    <%= link_to 'Back', :back, class:"back" %>
  </div>

<% end %>

app/views/medicines/index.html.erb
<p id="notice"><%= notice %></p>

<div class="posts-list">
  <h1 class="mypage-title">＜<%= @nickname %>さんの直近の処方管理記録＞</h1>
  <br>
  <% if @medicines.any? %>
    <table>
      <thead>
        <tr>
          <th>処方名</th>
          <th>処方日</th>
          <th>カテゴリ</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @medicines.each do |medicine| %>
          <tr>
            <td><%= link_to medicine.name, medicine %></td>
            <td><%= medicine.start_time.strftime("%Y-%m-%d") %></td>
            <td><%= raw(medicine.tag_list.map{ |t| link_to t, tag_path(t) }.join(', ')) %></td>
            <td><%= link_to '詳細', medicine %></td>
            <td><%= link_to '編集', edit_medicine_path(medicine.id) %></td>
            <td><%= link_to '削除',medicine_path(medicine.id), method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  <% else %>
    まだ記録がありません
  <% end %>
  <%= paginate @medicines %>
  <br>
  <ul>
    <li><%= link_to "薬を登録する", new_medicine_path, class: "medicine-post" %></li>
    <br>
    <li><%= link_to 'マイページへ戻る', "users/#{@user.id}", class:"back" %></li>
    <br>
    <% if params[:tag] %>
      <li><%= link_to '絞り込みを解除する', medicines_path, class:"back" %></li>
    <% end %>
  </ul>
</div>

app/views/medicines/new.html.erb
<%= form_with(model: @medicine, local: true) do |f| %>

  <% if @medicine.errors.any? %>
    <div class="error-alert">
      <ul>
        <% @medicine.errors.full_messages.each do |message| %>
        <li class='error-message'><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <br>

  <div class="date">
    <%= f.label :【処方日】 %>
    <br>
    <%= f.date_field :start_time, class:"date-form" %>
  </div>
  <br>

  <div class="medicine-name">
    <%= f.label :【処方名】 %>
    <br>
    <%= f.text_field :name, placeholder: "薬の名前を入力", class:"name-form" %>
  </div>
  <br>

  <div class="medicine-file">
    <%= f.label :【画像】 %>
    <br>
    <%= f.file_field :image, class:"file-form" %>
  </div>
  <br>

  <div class="medicine-tag">
    <%= f.label :【タグ】 %>
    <br>
    <%= f.text_field :tag_list, value: @medicine.tag_list.join(','), placeholder: "症状別にタグ付け", class:"tag-form" %>
    <p>※タグを複数加える場合は「,」でつなげてください。<br>　例）発熱,頭痛</p>
  </div>
  <br>

  <div class="memo">
    <%= f.label :【メモ】 %>
    <br>
    <%= f.text_field :memo, class:"memo-form" %>
  </div>
  <br>


  <div class="submit">
    <%= f.submit "登録" %>
  </div>
  <br>

  <div class="show-link">
    <%= link_to 'Back', :back, class:"back" %>
  </div>

<% end %>

app/views/medicines/show.html.erb
<p id="notice"><%= notice %></p>

<div class="show">
  <h1 class="mypage-title">＜<%= @medicine.name %>の登録詳細ページ＞</h1>
  <br>
  <table>
    <tr>
      <th><strong>【処方名】</strong></th><td><%= @medicine.name %></td>
    </tr>

    <tr>
      <th><strong>【処方日】</strong></th><td><%= @medicine.start_time.strftime("%Y-%m-%d") %></td>
    </tr>

    <tr>
      <th><strong>【タグ】</strong></th><td><%= raw(@medicine.tag_list.map { |t| link_to t, tag_path(t) }.join(', ')) %></td>
    </tr>

    <tr>
      <th><strong>【メモ】</strong></th><td><%= @medicine.memo %></td>
    </tr>

    <% if @medicine.image.attached? %>
      <tr>
        <th><strong>【登録画像】</strong></th><td><%= image_tag @medicine.image.variant(resize: '500x500'), class: 'medicine-image' if @medicine.image.attached? %></td>
      </tr>
    <% end %>
  </table>
</div>
<br>

<div class="show-link">
  <%= link_to '編集', edit_medicine_path(@medicine), class:"edit" %>
  <%= link_to 'Back', medicines_path, class:"back" %>
</div>