config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'posts#index'

  resources :posts do
    collection do
      get 'search'
    end
  end

  resources :users, only: :show

  resources :conditions do
    collection do
      get 'temp'
      get 'weight'
      get 'blood_max'
      get 'blood_min'
      get 'com'
    end
  end

  resources :medicines
  get 'tags/:tag', to: 'medicines#index', as: :tag
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts
  has_many :conditions
  has_many :medicines

  with_options presence: true do
    validates :nickname
    validates :birthday

    PASSWORD_REGEX = /\A(?=.*?[a-z])(?=.*?[\d])[a-z\d]+\z/i
    validates :password, format: { with: PASSWORD_REGEX, message: "半角英数混合で入力してください"}

    NAME_REGEX = /\A[ぁ-んァ-ン一-龥]/
    with_options format: { with: NAME_REGEX, message: "全角（漢字・ひらがな・カタカナ）で入力してください"} do
      validates :first_name
      validates :last_name
    end

    NAME_READING_REGEX = /\A[ァ-ヶー－]+\z/
      with_options format: { with: NAME_READING_REGEX, message: "全角（カタカナ）で入力してください"} do
        validates :first_name_reading
        validates :last_name_reading
      end
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @nickname = current_user.nickname
    @birthday = current_user.birthday
    @posts = current_user.posts.order("start_time DESC").page(params[:page]).per(3)
    @user = current_user

    #内科
    @post1 = Post.where(user_id: @user.id, category_id: 1).page(params[:page]).per(3)
    @category1 = Category.find(1)

    #外科
    @post2 = Post.where(user_id: @user.id, category_id: 2).page(params[:page]).per(3)
    @category2 = Category.find(2)

    #整形外科
    @post3 = Post.where(user_id: @user.id, category_id: 3).page(params[:page]).per(3)
    @category3 = Category.find(3)

    #皮膚科
    @post4 = Post.where(user_id: @user.id, category_id: 4).page(params[:page]).per(3)
    @category4 = Category.find(4)

    #眼科
    @post5 = Post.where(user_id: @user.id, category_id: 5).page(params[:page]).per(3)
    @category5 = Category.find(5)

    #耳鼻科
    @post6 = Post.where(user_id: @user.id, category_id: 6).page(params[:page]).per(3)
    @category6 = Category.find(6)

    #歯科
    @post7 = Post.where(user_id: @user.id, category_id: 7).page(params[:page]).per(3)
    @category7 = Category.find(7)

    #その他
    @post8 = Post.where(user_id: @user.id, category_id: 8).page(params[:page]).per(3)
    @category8 = Category.find(8)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/show.html.erb
<div class="mypage">

  <%= form_with(url: search_posts_path, local: true, method: :get, class: "search-form") do |form| %>
    <%= form.text_field :keyword, placeholder: "投稿を検索する", class: "search-input" %>
    <%= form.submit "検索", class: "search-btn" %>
  <% end %>
  <br>

  <div class="posts-list">
    <h1 class="mypage-title">＜<%= @nickname %>さんの直近の通院記録＞</h1>
    <br>
    <% if @posts.any? %>
      <table>
        <thead>
          <tr>
            <th>タイトル</th>
            <th>日付</th>
            <th colspan="3"></th>
          </tr>
        </thead>

        <tbody>
          <% @posts.each do |post| %>
            <tr>
              <td><%= link_to post.title, post %></td>
              <td><%= post.start_time.strftime("%Y-%m-%d") %></td>
              <td><%= link_to '詳細', post %></td>
              <td><%= link_to '編集', edit_post_path(post.id) %></td>
              <td><%= link_to '削除',post_path(post.id), method: :delete, data: { confirm: 'Are you sure?' } %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    <% else %>
      まだ投稿がありません
    <% end %>
    <%= paginate @posts %>
  </div>
  <br>
  <ul>
    <li><%= link_to '体調管理ページへ', conditions_path, class:"condition" %></li>
    <li><%= link_to '処方管理ページへ', medicines_path, class:"condition" %></li>
  </ul>
  <br>

  <%= week_calendar events: @posts do |date, posts| %>
    <%= date.day %>
    <% if posts.any? %>
      <% posts.each do |post| %>
        <div>
          <%= link_to post.title, post %>
        </div>
      <% end %>
    <% end %>
  <% end %>
  <br>


  <div class="category-area">
    <div class="category-list">
      <h1 class="mypage-title">＜<%= @category1.name %>の投稿一覧＞</h1>
      <br>
      <% if @post1.any? %>
        <table>
          <thead>
            <tr>
              <th>タイトル</th>
              <th>日付</th>
              <th colspan="3"></th>
            </tr>
          </thead>

          <tbody>
            <% @post1.each do |post| %>
              <tr>
                <td><%= post.title %></td>
                <td><%= post.start_time.strftime("%Y-%m-%d %H:%M") %></td>
                <td><%= link_to '詳細', post %></td>
                <td><%= link_to '編集', edit_post_path(post.id) %></td>
                <td><%= link_to '削除',post_path(post.id), method: :delete, data: { confirm: 'Are you sure?' } %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      <% else %>
        まだ投稿がありません
      <% end %>
      <%= paginate @post1 %>
    </div>
    <br>
    <br>

    <div class="category-list">
      <h1 class="mypage-title">＜<%= @category2.name %>の投稿一覧＞</h1>
      <br>
      <% if @post2.any? %>
        <table>
          <thead>
            <tr>
              <th>タイトル</th>
              <th>日付</th>
              <th colspan="3"></th>
            </tr>
          </thead>

          <tbody>
            <% @post2.each do |post| %>
              <tr>
                <td><%= post.title %></td>
                <td><%= post.start_time.strftime("%Y-%m-%d %H:%M") %></td>
                <td><%= link_to '詳細', post %></td>
                <td><%= link_to '編集', edit_post_path(post.id) %></td>
                <td><%= link_to '削除',post_path(post.id), method: :delete, data: { confirm: 'Are you sure?' } %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      <% else %>
        まだ投稿がありません
      <% end %>
      <%= paginate @post2 %>
    </div>
    <br>
    <br>

    <div class="category-list">
      <h1 class="mypage-title">＜<%= @category3.name %>の投稿一覧＞</h1>
      <br>
      <% if @post3.any? %>
        <table>
          <thead>
            <tr>
              <th>タイトル</th>
              <th>日付</th>
              <th colspan="3"></th>
            </tr>
          </thead>

          <tbody>
            <% @post3.each do |post| %>
              <tr>
                <td><%= post.title %></td>
                <td><%= post.start_time.strftime("%Y-%m-%d %H:%M") %></td>
                <td><%= link_to '詳細', post %></td>
                <td><%= link_to '編集', edit_post_path(post.id) %></td>
                <td><%= link_to '削除',post_path(post.id), method: :delete, data: { confirm: 'Are you sure?' } %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      <% else %>
        まだ投稿がありません
      <% end %>
      <%= paginate @post3 %>
    </div>
    <br>
    <br>

    <div class="category-list">
      <h1 class="mypage-title">＜<%= @category4.name %>の投稿一覧＞</h1>
      <br>
      <% if @post4.any? %>
        <table>
          <thead>
            <tr>
              <th>タイトル</th>
              <th>日付</th>
              <th colspan="3"></th>
            </tr>
          </thead>

          <tbody>
            <% @post4.each do |post| %>
              <tr>
                <td><%= post.title %></td>
                <td><%= post.start_time.strftime("%Y-%m-%d %H:%M") %></td>
                <td><%= link_to '詳細', post %></td>
                <td><%= link_to '編集', edit_post_path(post.id) %></td>
                <td><%= link_to '削除',post_path(post.id), method: :delete, data: { confirm: 'Are you sure?' } %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      <% else %>
        まだ投稿がありません
      <% end %>
      <%= paginate @post4 %>
    </div>
    <br>
    <br>

    <div class="category-list">
      <h1 class="mypage-title">＜<%= @category5.name %>の投稿一覧＞</h1>
      <br>
      <% if @post5.any? %>
        <table>
          <thead>
            <tr>
              <th>タイトル</th>
              <th>日付</th>
              <th colspan="3"></th>
            </tr>
          </thead>

          <tbody>
            <% @post5.each do |post| %>
              <tr>
                <td><%= post.title %></td>
                <td><%= post.start_time.strftime("%Y-%m-%d %H:%M") %></td>
                <td><%= link_to '詳細', post %></td>
                <td><%= link_to '編集', edit_post_path(post.id) %></td>
                <td><%= link_to '削除',post_path(post.id), method: :delete, data: { confirm: 'Are you sure?' } %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      <% else %>
        まだ投稿がありません
      <% end %>
      <%= paginate @post5 %>
    </div>
    <br>
    <br>

    <div class="category-list">
      <h1 class="mypage-title">＜<%= @category6.name %>の投稿一覧＞</h1>
      <br>
      <% if @post6.any? %>
        <table>
          <thead>
            <tr>
              <th>タイトル</th>
              <th>日付</th>
              <th colspan="3"></th>
            </tr>
          </thead>

          <tbody>
            <% @post6.each do |post| %>
              <tr>
                <td><%= post.title %></td>
                <td><%= post.start_time.strftime("%Y-%m-%d %H:%M") %></td>
                <td><%= link_to '詳細', post %></td>
                <td><%= link_to '編集', edit_post_path(post.id) %></td>
                <td><%= link_to '削除',post_path(post.id), method: :delete, data: { confirm: 'Are you sure?' } %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      <% else %>
        まだ投稿がありません
      <% end %>
      <%= paginate @post6 %>
    </div>
    <br>
    <br>

    <div class="category-list">
      <h1 class="mypage-title">＜<%= @category7.name %>の投稿一覧＞</h1>
      <br>
      <% if @post7.any? %>
        <table>
          <thead>
            <tr>
              <th>タイトル</th>
              <th>日付</th>
              <th colspan="3"></th>
            </tr>
          </thead>

          <tbody>
            <% @post7.each do |post| %>
              <tr>
                <td><%= post.title %></td>
                <td><%= post.start_time.strftime("%Y-%m-%d %H:%M") %></td>
                <td><%= link_to '詳細', post %></td>
                <td><%= link_to '編集', edit_post_path(post.id) %></td>
                <td><%= link_to '削除',post_path(post.id), method: :delete, data: { confirm: 'Are you sure?' } %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      <% else %>
        まだ投稿がありません
      <% end %>
      <%= paginate @post7 %>
    </div>
    <br>
    <br>

    <div class="category-list">
      <h1 class="mypage-title">＜<%= @category8.name %>の投稿一覧＞</h1>
      <br>
      <% if @post8.any? %>
        <table>
          <thead>
            <tr>
              <th>タイトル</th>
              <th>日付</th>
              <th colspan="3"></th>
            </tr>
          </thead>

          <tbody>
            <% @post8.each do |post| %>
              <tr>
                <td><%= post.title %></td>
                <td><%= post.start_time.strftime("%Y-%m-%d %H:%M") %></td>
                <td><%= link_to '詳細', post %></td>
                <td><%= link_to '編集', edit_post_path(post.id) %></td>
                <td><%= link_to '削除',post_path(post.id), method: :delete, data: { confirm: 'Are you sure?' } %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      <% else %>
        まだ投稿がありません
      <% end %>
      <%= paginate @post8 %>
    </div>
    <br>

  </div>
</div>