config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'posts#index'

  resources :posts do
    collection do
      get 'search'
    end
  end

  resources :users, only: :show

  resources :conditions do
    collection do
      get 'temp'
      get 'weight'
      get 'blood_max'
      get 'blood_min'
      get 'com'
    end
  end

  resources :medicines
  get 'tags/:tag', to: 'medicines#index', as: :tag
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>通院calendar</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css" integrity="sha384-oS3vJWv+0UjzBfQzYUhtDYW+Pj2yciDJxpsK1OYPAYjqT085Qq/1cq5FLXAZQ7Ay" crossorigin="anonymous">
  </head>

  <body>
    <header class="header">
      <div class="header__bar row">
        <h1 class="grid-6"><a href="/">Calendar</a></h1>
        <% if user_signed_in? %>
          <div class="user_nav grid-6">
            <%= link_to '体調管理', conditions_path, class:"condition" %>
            <%= link_to '処方管理', medicines_path, class:"condition" %>
            <%= link_to current_user.nickname, "/users/#{current_user.id}", class: "user-nickname" %>
            <%= link_to "ログアウト", destroy_user_session_path, method: :delete %>
            <%= link_to "投稿する", new_post_path, class: "post" %>
          </div>
        <% else %>
          <div class="grid-6">
            <%= link_to "ログイン", new_user_session_path, class: "post" %>
            <%= link_to "新規登録", new_user_registration_path, class: "post" %>
          </div>
        <% end %>
      </div>
    </header>

    <%= yield %>

    <footer>
      <p>
        Copyright Calendar 2020.
      </p>
    </footer>
  </body>
</html>